[package]
name = "mhttp"
version = "0.1.0"
edition = "2021"
authors = [ "David Hoppenbrouwers <mhttp@demindiro.com>" ]
description = "Utilities for building & parsing HTTP requests & responses in no_std environments."
repository = "https://git.sr.ht/~demindiro/mhttp"
license = "MIT"
